
### Register admin user
POST http://localhost:8087/api/users/
Content-Type: application/json

{
  "username": "aaa",
  "password": "aa",
  "fullName": "Admin User",
  "role": "admin"
}

###

### Register customer user
POST http://localhost:8087/api/users/
Content-Type: application/json

{
  "username": "bbb",
  "password": "bb",
  "fullName": "Customer User",
  "role": "customer"
}

### Delete 
DELETE http://localhost:8087/api/users/rishitha
Authorization: Basic manvitha:manv
###

     